# Generated by Django 3.1 on 2020-09-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200909_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_pic',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
