# Generated by Django 3.1 on 2020-09-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200909_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
