# Generated by Django 3.1 on 2021-01-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201210_2026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchQuery',
        ),
    ]
